# Generated by Django 4.2.2 on 2024-11-04 14:12

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="Введите номер телефона",
                max_length=11,
                unique=True,
                validators=[users.validators.phone_validator],
                verbose_name="Телефон",
            ),
        ),
    ]
