# Generated by Django 4.2.2 on 2024-11-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="sms",
        ),
    ]
