# Generated by Django 4.2.2 on 2024-11-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_sms"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sms",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Одноразовый СМС-код"
            ),
        ),
    ]
