# Generated by Django 4.2.2 on 2024-11-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_sms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="Введите номер телефона",
                max_length=11,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
    ]
